//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caredev.Mego.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Caredev.Mego.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 匿名对象属性是只读属性不能修改。 的本地化字符串。
        /// </summary>
        internal static string ExceptionAnonymousObjectPropertyIsReadOnly {
            get {
                return ResourceManager.GetString("ExceptionAnonymousObjectPropertyIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二元逻辑操作种类非法，只支持AndAlso和OrElse。 的本地化字符串。
        /// </summary>
        internal static string ExceptionBinaryLogicalKind {
            get {
                return ResourceManager.GetString("ExceptionBinaryLogicalKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 集合属性层级错误，集合属性一般是最底层级。 的本地化字符串。
        /// </summary>
        internal static string ExceptionCollectionMemberLevelError {
            get {
                return ResourceManager.GetString("ExceptionCollectionMemberLevelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定提交多个的数据对象已被并发更改。 的本地化字符串。
        /// </summary>
        internal static string ExceptionCommitConcurrency {
            get {
                return ResourceManager.GetString("ExceptionCommitConcurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前连接状态错误，期望连接为Open。 的本地化字符串。
        /// </summary>
        internal static string ExceptionConnectionStateError {
            get {
                return ResourceManager.GetString("ExceptionConnectionStateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前方法只能在LINQ表达式中使用，禁止直接调用。 的本地化字符串。
        /// </summary>
        internal static string ExceptionDisableInvode {
            get {
                return ResourceManager.GetString("ExceptionDisableInvode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 映射到数据库的函数名不能为空。 的本地化字符串。
        /// </summary>
        internal static string ExceptionFunctionNameCannotEmpty {
            get {
                return ResourceManager.GetString("ExceptionFunctionNameCannotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Func类型参数数量非法。 的本地化字符串。
        /// </summary>
        internal static string ExceptionFuncTypeArgumentNumberError {
            get {
                return ResourceManager.GetString("ExceptionFuncTypeArgumentNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成内容必须是SELECT表达式。 的本地化字符串。
        /// </summary>
        internal static string ExceptionGenerateContentIsSelect {
            get {
                return ResourceManager.GetString("ExceptionGenerateContentIsSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成内容单元项必须是NEW表达式。 的本地化字符串。
        /// </summary>
        internal static string ExceptionGenerateUnitItemIsNew {
            get {
                return ResourceManager.GetString("ExceptionGenerateUnitItemIsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化 New 表达式时父级输出对象不能为空。 的本地化字符串。
        /// </summary>
        internal static string ExceptionInitialNewParentIsNull {
            get {
                return ResourceManager.GetString("ExceptionInitialNewParentIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插入的内容必须是 SELECT 表达式。 的本地化字符串。
        /// </summary>
        internal static string ExceptionInsertContentIsSelect {
            get {
                return ResourceManager.GetString("ExceptionInsertContentIsSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插入的单元项必须是 New 表达式。 的本地化字符串。
        /// </summary>
        internal static string ExceptionInsertItemIsMustNew {
            get {
                return ResourceManager.GetString("ExceptionInsertItemIsMustNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器版本 {0} 转换无效。 的本地化字符串。
        /// </summary>
        internal static string ExceptionInvalidCastServerVersion {
            get {
                return ResourceManager.GetString("ExceptionInvalidCastServerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效索引对象。 的本地化字符串。
        /// </summary>
        internal static string ExceptionInvalidIndexObject {
            get {
                return ResourceManager.GetString("ExceptionInvalidIndexObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前表达式必须是有效的数据集对象。 的本地化字符串。
        /// </summary>
        internal static string ExceptionIsMustDbSetInstance {
            get {
                return ResourceManager.GetString("ExceptionIsMustDbSetInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前表达式类型必须是无参构造函数。 的本地化字符串。
        /// </summary>
        internal static string ExceptionIsMustParameterlessConstructor {
            get {
                return ResourceManager.GetString("ExceptionIsMustParameterlessConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前数据对象类型 {0} 不是继承类型。 的本地化字符串。
        /// </summary>
        internal static string ExceptionIsNotInheritSet {
            get {
                return ResourceManager.GetString("ExceptionIsNotInheritSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前表达式不是一元操作表达式。 的本地化字符串。
        /// </summary>
        internal static string ExceptionIsNotUnaryExpression {
            get {
                return ResourceManager.GetString("ExceptionIsNotUnaryExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前表达式不是单元类型表达式。 的本地化字符串。
        /// </summary>
        internal static string ExceptionIsNotUnitType {
            get {
                return ResourceManager.GetString("ExceptionIsNotUnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所声明的关系主键与外键数量不匹配。 的本地化字符串。
        /// </summary>
        internal static string ExceptionKeyCountIsNotMatch {
            get {
                return ResourceManager.GetString("ExceptionKeyCountIsNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lambda 表达式中不包含有效的成员访问节点。 的本地化字符串。
        /// </summary>
        internal static string ExceptionLambdaFoundNotMemberAccess {
            get {
                return ResourceManager.GetString("ExceptionLambdaFoundNotMemberAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lambda 表达式中找不到相应的 PropertyInfo 成员对象。 的本地化字符串。
        /// </summary>
        internal static string ExceptionLambdaFoundNotPropertyInfo {
            get {
                return ResourceManager.GetString("ExceptionLambdaFoundNotPropertyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成员路径不能为空。 的本地化字符串。
        /// </summary>
        internal static string ExceptionMemberPathCannotEmpty {
            get {
                return ResourceManager.GetString("ExceptionMemberPathCannotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前查找的成员不能与目标成员相同。 的本地化字符串。
        /// </summary>
        internal static string ExceptionMemberSourceMatch {
            get {
                return ResourceManager.GetString("ExceptionMemberSourceMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前查找的成员所在的数据源父级不能为空。 的本地化字符串。
        /// </summary>
        internal static string ExceptionMemberSourceParentIsNulll {
            get {
                return ResourceManager.GetString("ExceptionMemberSourceParentIsNulll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合并的语句块不能为空。 的本地化字符串。
        /// </summary>
        internal static string ExceptionMergeFragmentIsNotEmpty {
            get {
                return ResourceManager.GetString("ExceptionMergeFragmentIsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对于 {0} 数据提供者找不到适用于版本 0x{1:X4} 的 SQL 生成器对象。 的本地化字符串。
        /// </summary>
        internal static string ExceptionNotFoundGenerator {
            get {
                return ResourceManager.GetString("ExceptionNotFoundGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对于 {0} 数据提供者找不到适用于版本 0x{1:X4} 的 SQL 生成器对象。 的本地化字符串。
        /// </summary>
        internal static string ExceptionNotFoundGenerator1 {
            get {
                return ResourceManager.GetString("ExceptionNotFoundGenerator1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到 {0} 相应的 SQL 生成器对象集。 的本地化字符串。
        /// </summary>
        internal static string ExceptionNotFoundGeneratorCollection {
            get {
                return ResourceManager.GetString("ExceptionNotFoundGeneratorCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到 {0} 相应的 SQL 生成器对象集。 的本地化字符串。
        /// </summary>
        internal static string ExceptionNotFoundGeneratorCollection1 {
            get {
                return ResourceManager.GetString("ExceptionNotFoundGeneratorCollection1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前表达式没有找到Lammbda表达式。 的本地化字符串。
        /// </summary>
        internal static string ExceptionNotFoundLambdaExpression {
            get {
                return ResourceManager.GetString("ExceptionNotFoundLambdaExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前表达式不包含Lambda表达式。 的本地化字符串。
        /// </summary>
        internal static string ExceptionNotFoundLambdaExpression1 {
            get {
                return ResourceManager.GetString("ExceptionNotFoundLambdaExpression1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到指定命名的的导航成员。 的本地化字符串。
        /// </summary>
        internal static string ExceptionNotFoundNavigateKey {
            get {
                return ResourceManager.GetString("ExceptionNotFoundNavigateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到名为 {0} 的数据访问提供程序。 的本地化字符串。
        /// </summary>
        internal static string ExceptionNotFoundProvider {
            get {
                return ResourceManager.GetString("ExceptionNotFoundProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前对象已释放。 的本地化字符串。
        /// </summary>
        internal static string ExceptionObjectIsDisposed {
            get {
                return ResourceManager.GetString("ExceptionObjectIsDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前输出对象必须要包含有效数据。 的本地化字符串。
        /// </summary>
        internal static string ExceptionOutputMustHasRows {
            get {
                return ResourceManager.GetString("ExceptionOutputMustHasRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前输出对象只能包含一个有效数据。 的本地化字符串。
        /// </summary>
        internal static string ExceptionOutputMustOnlyOne {
            get {
                return ResourceManager.GetString("ExceptionOutputMustOnlyOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 映射到数据库的表名不能为空。 的本地化字符串。
        /// </summary>
        internal static string ExceptionTableNameCannotEmpty {
            get {
                return ResourceManager.GetString("ExceptionTableNameCannotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的类型不是有效的枚举类型。 的本地化字符串。
        /// </summary>
        internal static string ExceptionTypeIsNotEnum {
            get {
                return ResourceManager.GetString("ExceptionTypeIsNotEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语句查询单元项必须是数据项。 的本地化字符串。
        /// </summary>
        internal static string ExceptionUnitItemIsMustDataItem {
            get {
                return ResourceManager.GetString("ExceptionUnitItemIsMustDataItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持循环依赖的操作。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedCircularDependenceOperate {
            get {
                return ResourceManager.GetString("NotSupportedCircularDependenceOperate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持访问非当前数据上下文的数据集对象。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedContextIsNotMatch {
            get {
                return ResourceManager.GetString("NotSupportedContextIsNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持创建类型 {0} 的插入成员。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedCreateInsertMember {
            get {
                return ResourceManager.GetString("NotSupportedCreateInsertMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持创建类型 {0} 的维护语句片段。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedCreateMaintenance {
            get {
                return ResourceManager.GetString("NotSupportedCreateMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持创建类型 {0} 成员。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedCreateMember {
            get {
                return ResourceManager.GetString("NotSupportedCreateMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持创建类型 {0} 的数据源语句片段。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedCreateSource {
            get {
                return ResourceManager.GetString("NotSupportedCreateSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持类型为 {0} 的表达式解析为内连接连接条件。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedExpressionParseInnerJoinKeyPairs {
            get {
                return ResourceManager.GetString("NotSupportedExpressionParseInnerJoinKeyPairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持循解析表达式为值类型表达式。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedExpressionParseValueType {
            get {
                return ResourceManager.GetString("NotSupportedExpressionParseValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持的成员值生成选项 {0} 。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedGeneratedOption {
            get {
                return ResourceManager.GetString("NotSupportedGeneratedOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持生成类型 {0} 的表达式。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedGenerateExpression {
            get {
                return ResourceManager.GetString("NotSupportedGenerateExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持类型 {0} 的维护操作生成语句片段。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedGenerateMaintenance {
            get {
                return ResourceManager.GetString("NotSupportedGenerateMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持从类型 {0} 表达式中获取获取查询主体。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedGetQueryBody {
            get {
                return ResourceManager.GetString("NotSupportedGetQueryBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持从类型 {0} 表达式中获取获取查询列表。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedGetQueryList {
            get {
                return ResourceManager.GetString("NotSupportedGetQueryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持解析当前单元项作为展开项。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedIncludeUnitItem {
            get {
                return ResourceManager.GetString("NotSupportedIncludeUnitItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持在继承的数据对象中使用自定义数据库名称。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedInheritSetUsingDbName {
            get {
                return ResourceManager.GetString("NotSupportedInheritSetUsingDbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持初始化类型 {0} 的成员。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedInitialMember {
            get {
                return ResourceManager.GetString("NotSupportedInitialMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持初始化 New 中类型 {0} 的成员。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedInitialNewValue {
            get {
                return ResourceManager.GetString("NotSupportedInitialNewValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持初始化类型 {0} 的检索函数。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedInitialRetrieval {
            get {
                return ResourceManager.GetString("NotSupportedInitialRetrieval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持实体化类型 {0} 。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedInstanceType {
            get {
                return ResourceManager.GetString("NotSupportedInstanceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持连接类型 {0} 的虚拟数据源。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedJoinVirtualSource {
            get {
                return ResourceManager.GetString("NotSupportedJoinVirtualSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持加载非 DbRelationItem 类型的数据。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedLoadNotRelationItem {
            get {
                return ResourceManager.GetString("NotSupportedLoadNotRelationItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持在New表达式中使用 {0} 成员绑定类型。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedNewMemberBindingType {
            get {
                return ResourceManager.GetString("NotSupportedNewMemberBindingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持直接检索表达式成员。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedOnlyRetrievalForExpression {
            get {
                return ResourceManager.GetString("NotSupportedOnlyRetrievalForExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持输出 {0} 类型的数据。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedOutpputClrType {
            get {
                return ResourceManager.GetString("NotSupportedOutpputClrType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持解析当前表达式。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedParseExpression {
            get {
                return ResourceManager.GetString("NotSupportedParseExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持解析当前表达式做为成员访问。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedParseExpressionToMemberAccess {
            get {
                return ResourceManager.GetString("NotSupportedParseExpressionToMemberAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持解析当前表达式做为一元运算。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedParseExpressionToUnary {
            get {
                return ResourceManager.GetString("NotSupportedParseExpressionToUnary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持解析该类型 {0} 的Lammbda表达式节点。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedParseLambdaNodeType {
            get {
                return ResourceManager.GetString("NotSupportedParseLambdaNodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持循解析类型 {0} 的 Lambda 表达式。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedParseLambdaNodeType1 {
            get {
                return ResourceManager.GetString("NotSupportedParseLambdaNodeType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持解析类型 {0} 操作。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedParseOperate {
            get {
                return ResourceManager.GetString("NotSupportedParseOperate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持解析当前表达式做为单元项。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedParseUnitItem {
            get {
                return ResourceManager.GetString("NotSupportedParseUnitItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持解析当前表达式作为单元类型。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedParseUnitType {
            get {
                return ResourceManager.GetString("NotSupportedParseUnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持检索类型 {0} 的成员。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedRetrievalMember {
            get {
                return ResourceManager.GetString("NotSupportedRetrievalMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持检索 New 表达式中类型 {0} 成员。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedRetrievalNewValue {
            get {
                return ResourceManager.GetString("NotSupportedRetrievalNewValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持检索虚拟列表中中类型 {0} 表达式。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedRetrievalVirtualList {
            get {
                return ResourceManager.GetString("NotSupportedRetrievalVirtualList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持类型为 {0} 的单元表达式项为对象成员。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedUnitExpressionToObjectMember {
            get {
                return ResourceManager.GetString("NotSupportedUnitExpressionToObjectMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前单元表达式不能展开子成员。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedUnitIsNotExpandUnit {
            get {
                return ResourceManager.GetString("NotSupportedUnitIsNotExpandUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持写入类型 {0} 的数据库对象语句片段。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedWriteDatabaseObject {
            get {
                return ResourceManager.GetString("NotSupportedWriteDatabaseObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持写入数据类型 {0} 。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedWriteDbDataType {
            get {
                return ResourceManager.GetString("NotSupportedWriteDbDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持写入类型 {0} 的语句片段。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedWriteFragment {
            get {
                return ResourceManager.GetString("NotSupportedWriteFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持写入类型 {0} 的聚合函数语句片段。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedWriteFragmentForAggregate {
            get {
                return ResourceManager.GetString("NotSupportedWriteFragmentForAggregate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持写入类型 {0} 的二元运算语句片段。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedWriteFragmentForBinary {
            get {
                return ResourceManager.GetString("NotSupportedWriteFragmentForBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持写入类型 {0} 的标量函数语句片段。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedWriteFragmentForScalar {
            get {
                return ResourceManager.GetString("NotSupportedWriteFragmentForScalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持写入表变量语句片段 。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedWriteTableVariable {
            get {
                return ResourceManager.GetString("NotSupportedWriteTableVariable", resourceCulture);
            }
        }
    }
}
